### ISSUE TITLE
Flow will never be presented if the view controller has no navigation controller

### ISSUE THREAD

**Issue by jimspeth** [Autodesk/ADAppRater-iOS#14]
Starting the flow from a view controller that is not in a UINavigationController does not work because the check to see if the view controller is visible fails.

This line:
https://github.com/Autodesk/ADAppRater-iOS/blob/master/ADAppRater/ADAppRater.m#L836
should check that `viewController.navigationController` is not nil before comparing to `viewController`.

**Comment by antongaenko** [comment]
found the same issue today and wrote the same check, +1 to merge this PR

**Comment by ashavit** [comment]
Pushed now to version 1.0.5.
Thnx
