### ISSUE TITLE
iOS 10 support for rating api / new rules

### ISSUE THREAD

**Issue by JulesMoorhouse** [Autodesk/ADAppRater-iOS#25]
Hi

Does this framework fall back to the new iOS 10 rules on review and use the new rating api?

Thanks

Jules

**Comment by ashavit** [comment]
Hi jules,
It does not. 
The new rating API is really cool, but as Apple suggests not to use it as a reaction.
Our rating tool is based on internal user flows and conditions defined by you.
Apple says: 
> Although you should call this method when it makes sense in the user experience flow of your app, the actual display of a rating/review request view is governed by App Store policy. Because this method may or may not present an alert, it's not appropriate to call it in response to a button tap or other user action

Amir

**Comment by JulesMoorhouse** [comment]
In that case when can the new api be used ?
Surely every use is triggered by user action ?

**Comment by ashavit** [comment]
What Apple suggests is to call it when you would like to prompt the user to rate your app (maybe he successfully finishes some kind of app flow), but don't count on it.
Don't base the rest of your flow on the assumption the rating screen was displayed. 
If you try to display it as a button action and it doesn't show - your app will look silly. Therefore we decided to keep working with our old flow and not adopt the new API so we can still takr the user to rate on the store (when he agrees by pressing a button).

**Comment by JulesMoorhouse** [comment]
I actually found this which does what I want.

https://github.com/takecian/SwiftRater/blob/master/README.md

It allows me to display the Rate dialog after 5 significant events, but not directly after, the user then has to go to another screen before it's shown.
