### ISSUE TITLE
localStrings is private

### ISSUE THREAD

**Issue by qwertme** [Autodesk/ADAppRater-iOS#4]
The documentation states that you can set the feedback email by using:
ADAppRaterTexts\* newStrings = [[ADAppRaterTexts alloc] initWithApplicationName:@"App Name" feedbackRecipientEmail:@"support@your.mail"];
[ADAppRater sharedInstance].localStrings = newStrings;

But localStrings is private

**Comment by ashavit** [comment]
@qwertme Thanx for the feedback. Fixed it. I'll push an updated pod version soon. In the meanwhile you can point the pos the the master branch:

```
pod 'ADAppRater', :git => 'https://github.com/Autodesk/ADAppRater-iOS.git', :branch => 'master'
```
